### ISSUE TITLE
mod deps missing from metadata.json

### ISSUE THREAD

**Issue by jhoblitt** [Puppet-Finland/puppet-ipa#17]
The deps listed in `.fixtures.yml` and needed to use this mod but only the `stdlib` dep is present in `metadata.json`.
```
 fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib"
  forge_modules:
    cron_core:
      repo: "puppetlabs/cron_core"
      ref: "1.0.0"
      puppet_version: ">= 6.0.0"
    k5login_core:
      repo: "puppetlabs/k5login_core"
      ref: "1.0.2"
      puppet_version: ">= 6.0.0"
```
